# Ubuntu 22.04 and Cuda 12.4.1
FROM mambaorg/micromamba:ubuntu24.10

# activate micromamba env
ARG MAMBA_DOCKERFILE_ACTIVATE=1

# pypi dependacies
COPY requirements-cpu.txt /tmp/requirements-cpu.txt

RUN micromamba install -y -n base python=3.11

# install the python deps
RUN python -m pip install --no-cache-dir -r /tmp/requirements-cpu.txt --extra-index-url https://download.pytorch.org/whl/cpu

# copy over the chat templates
COPY chat-templates /chat-templates

# copy over the entry point
COPY --chown=$MAMBA_USER:$MAMBA_USER entrypoint.sh /
RUN chmod +x /entrypoint.sh
CMD ["/entrypoint.sh"]
